# Site settings
title: Chelsea Liu
email: chelsea.liu@edu.uwaterloo.ca #your-email@domain.com
url: https://chelsealiu.me
description: ":)"

# Color settings (hex-codes without the leading hash-tag)
color:
  primary-dark: '#000000'
  links: '#219ab3'

# Footer settings
footer: ChelseaLiu

# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
social:
  #- title: twitter
    #url: https://twitter.com/SBootstrap
  #- title: facebook
    #url:
  #- title: stack-overflow
    #url: http://stackoverflow.com/questions/tagged/jekyll
  #- title: bitbucket
    #url: http://bitbucket.org/jekyll
  - title: github
    url: https://github.com/zchelseal
  - title: linkedin
    url: https://www.linkedin.com/in/chelsea-l-32772082/

# Build settings
markdown: kramdown
permalink: pretty
