# Site settings
title: Chelsea Liu
email: chelsea.liu@edu.uwaterloo.ca #your-email@domain.com
url: https://chelsealiu.me
description: "Chorister, Coder, and Data Enthusiast :)"

# Color settings (hex-codes without the leading hash-tag)
color:
  primary-dark: '#000000'
  links: '#219ab3'

# Footer settings
footer: ChelseaLiu

# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
social:
  #- title: twitter
    #url: https://twitter.com/SBootstrap
  #- title: facebook
    #url:
  #- title: bitbucket
    #url: http://bitbucket.org/jekyll
  - title: linkedin
    url: https://www.linkedin.com/in/chelsea-l-32772082/
  - title: github
    url: https://github.com/zchelseal
  - title: stack-overflow
    url: https://stackoverflow.com/users/8535632/chelsea-liu
  #- title: angel-list
    #url: https://angel.co/chelsea-liu-2
  #- title: dev-post
    #url: https://devpost.com/ChelseaLiu?ref_content=user-portfolio&ref_feature=portfolio&ref_medium=global-nav

# Build settings
markdown: kramdown
permalink: pretty
